language: go

arch:
  - amd64
  - arm64
  - ppc64le
  - s390x

go:
  - 1.13.x

sudo: required

services:
  - docker
before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_USERNAME "| docker login --username=$HEROKU_USERNAME  --password=$HEROKU_API_KEY registry.heroku.com
script:
  - /bin/sh -c './build/build.sh'
  - /bin/sh -c 'if [ -f ./build/build_$TRAVIS_CPU_ARCH.sh ]; then eval ./build/build_$TRAVIS_CPU_ARCH.sh ; fi'
deploy:
  skip_cleanup: true
  provider: script
  script:
    # push to dockerhub & heroku
    - docker push gabrielbo1/iroko-$TRAVIS_CPU_ARCH:${TAG};
    - /bin/sh -c 'if [ -f ./build/push_$TRAVIS_CPU_ARCH.sh ]; then eval ./build/push_$TRAVIS_CPU_ARCH.sh ; fi'
  on:
    branch: master
